import = ["~/.config/alacritty/themes/tokyonight-night.toml"]

live_config_reload = true

[window]
decorations = "None"
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
padding = { x = 7, y = 0}

[font]
size = 15
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }

[cursor]
style = { blinking = "On" }
