require "pablobfonseca.globals"
require "pablobfonseca.options"
require "pablobfonseca.mappings"
require "pablobfonseca.autocmds"
require "pablobfonseca.lsp"

-- plugins
require "plugins.tokyonight"
require "plugins.treesitter"
require "plugins.telescope"
require "plugins.dressing"
require "plugins.lualine"
require "plugins.gitsigns"
require "plugins.oil"
require "plugins.mini"
require "plugins.mason"
require "plugins.conform"
require "plugins.cmp"
require "plugins.bqf"
require "plugins.text-case"
require "plugins.tmux-navigator"
require "plugins.dap"

require "pablobfonseca.lsp.ui"
