#!/usr/bin/env bash
# Feeds each guard the JSON its CLI sends and prints one line per case: Claude Code and Codex send
# PreToolUse (Codex's shell is Bash, its edits apply_patch), Gemini CLI sends BeforeTool
# (run_shell_command, write_file, replace). `decision` reads either deny shape; `shape` names which
# shape came back, or `silent` for no output and `empty-json` for {}.
set -u
H=${HOOKS:-$HOME/.dotfiles/claude/hooks}
# GUARD_BASH runs the guards under that interpreter instead of their shebang; the last line reruns
# every case under macOS's bash 3.2, which `env bash` resolves to when Homebrew's is not on PATH.
guard() { ${GUARD_BASH:-} "$H/$1"; }
decision() { local out; out=$(cat); [[ -z $out ]] && echo allow || jq -r '.decision // .hookSpecificOutput.permissionDecision // "allow"' <<<"$out" 2>/dev/null; }
shape() { local out; out=$(cat); [[ -z $out ]] && echo silent || jq -r 'if .decision then "gemini" elif .hookSpecificOutput then "claude" else "empty-json" end' <<<"$out" 2>/dev/null; }
fail=0
case_() { # name expected actual
  if [[ $2 == "$3" ]]; then echo "PASS $1"; else echo "FAIL $1: expected $2, got '$3'"; fail=1; fi
}
payload() { # event tool key value [cwd]
  jq -cn --arg e "$1" --arg t "$2" --arg k "$3" --arg v "$4" --arg c "${5:-}" '{hook_event_name:$e,tool_name:$t,tool_input:{($k):$v},cwd:$c}'
}
qv() { payload PreToolUse "$1" "$2" "$3" "${4:-}" | guard guard-queue-views.sh | decision; }
gv() { payload BeforeTool "$1" "$2" "$3" "${4:-}" | guard guard-queue-views.sh | decision; }
mg() { payload PreToolUse Bash command "$1" | guard guard-merge.sh | decision; }
gm() { payload BeforeTool run_shell_command command "$1" | guard guard-merge.sh | decision; }
unreadable() { jq -cn --arg e "$1" --arg t "$2" '{hook_event_name:$e,tool_name:$t,tool_input:"x",cwd:""}'; } # <event> <tool>: tool_input is a string, so jq reads no command, patch or path from it
many() { local i; for ((i = 0; i < $1; i++)); do printf "$2" "$i"; done; } # <n> <printf format>: the format n times, %d the index
patch() { printf '*** Begin Patch\n*** %s File: %s\n@@\n-a\n+b\n*** End Patch\n' "$1" "$2"; }
ipatch() { printf '*** Begin Patch\n  *** %s File: %s\n@@\n-a\n+b\n*** End Patch\n' "$1" "$2"; }
mpatch() { printf '*** Begin Patch\n*** Update File: %s\n*** Move to: %s\n@@\n-a\n+b\n*** End Patch\n' "$1" "$2"; }
V=$HOME/obsidian/SecondBrain/projects/ClaudeOS
Q=$HOME/.local/share/vault-queues/ClaudeOS
case_ "edit vault view"        deny  "$(qv Edit file_path "$V/Queue.md")"
case_ "write vault view"       deny  "$(qv Write file_path "$V/Queue.md")"
case_ "write authority"        deny  "$(qv Write file_path "$Q/Queue.md")"
T=$(mktemp -d)/vault-queues
mkdir -p "$T/.git/queue-tool-edit" "$T/ClaudeOS" "$T/Tribemap"
touch "$T/.git/queue-tool-edit/ClaudeOS"
case_ "edit authority, no session"    deny  "$(qv Edit file_path "$T/Tribemap/Queue.md")"
case_ "edit authority, open session"  allow "$(qv Edit file_path "$T/ClaudeOS/Queue.md")"
case_ "write authority, open session" deny  "$(qv Write file_path "$T/ClaudeOS/Queue.md")"
case_ "bash authority, open session"  deny  "$(qv Bash command "sed -i '' 's/a/b/' $T/ClaudeOS/Queue.md")"
case_ "edit session via dotdot"       deny  "$(qv Edit file_path "$T/ClaudeOS/../Tribemap/Queue.md")"
case_ "edit dotdot into session"      allow "$(qv Edit file_path "$T/Tribemap/../ClaudeOS/Queue.md")"
case_ "write view via dot"            deny  "$(qv Write file_path "$V/./Queue.md")"
case_ "write view via dotdot"         deny  "$(qv Write file_path "$V/plans/../Queue.md")"
case_ "dotdot past root"              deny  "$(qv Edit file_path "/../../$T/Tribemap/Queue.md")"
case_ "edit relative, open session"   deny  "$(qv Edit file_path "vault-queues/ClaudeOS/Queue.md")"
# --- codex: PreToolUse, shell as Bash, edits as apply_patch with the patch in tool_input.command
case_ "codex apply_patch update authority, open session"   allow "$(qv apply_patch command "$(patch Update "$T/ClaudeOS/Queue.md")")"
case_ "codex apply_patch relative authority, open session" allow "$(qv apply_patch command "$(patch Update ClaudeOS/Queue.md)" "$T")"
case_ "codex apply_patch relative authority, no session"   deny  "$(qv apply_patch command "$(patch Update Tribemap/Queue.md)" "$T")"
case_ "codex apply_patch delete authority, open session"   deny  "$(qv apply_patch command "$(patch Delete "$T/ClaudeOS/Queue.md")")"
case_ "codex apply_patch two files, one without session"   deny  "$(qv apply_patch command "$(patch Update "$T/ClaudeOS/Queue.md")$(patch Update "$T/Tribemap/Queue.md")")"
case_ "codex apply_patch indented header, no session"      deny  "$(qv apply_patch command "$(ipatch Update Tribemap/Queue.md)" "$T")"
case_ "codex apply_patch indented header, open session"    allow "$(qv apply_patch command "$(ipatch Update "$T/ClaudeOS/Queue.md")")"
case_ "codex apply_patch move onto authority, open session" deny "$(qv apply_patch command "$(mpatch README.md ClaudeOS/Queue.md)" "$T")"
case_ "codex apply_patch move authority away, open session" deny "$(qv apply_patch command "$(mpatch ClaudeOS/Queue.md ClaudeOS/old.md)" "$T")"
# --- gemini: BeforeTool, replace and write_file carry file_path, run_shell_command carries command
case_ "gemini replace authority, open session"          allow "$(gv replace file_path "$T/ClaudeOS/Queue.md")"
case_ "gemini replace relative authority, open session" allow "$(gv replace file_path ClaudeOS/Queue.md "$T")"
case_ "gemini replace relative authority, no session"   deny  "$(gv replace file_path Tribemap/Queue.md "$T")"
case_ "gemini write_file authority, open session"       deny  "$(gv write_file file_path "$T/ClaudeOS/Queue.md")"
case_ "edit lower-case name, open session"              deny  "$(qv Edit file_path "$T/ClaudeOS/queue.md")"
rm -rf "${T%/vault-queues}"
case_ "bash sed authority"     deny  "$(qv Bash command "sed -i 's/a/b/' $Q/Queue.md")"
case_ "bash heredoc view"      deny  "$(qv Bash command "cat > $V/Queue.md <<'X'")"
case_ "bash sed relative view" deny  "$(qv Bash command "sed -i '' 's/a/b/' projects/ClaudeOS/Queue.md")"
case_ "bash icloud view"       deny  "$(qv Bash command "sed -i '' 's/a/b/' '$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents/SecondBrain/projects/ClaudeOS/Queue.md'")"
case_ "edit inbox"             allow "$(qv Edit file_path "$V/Inbox.md")"
case_ "edit a plan"            allow "$(qv Edit file_path "$V/plans/2026-09-16-mechanical-rules.md")"
case_ "bash queue dump"        allow "$(qv Bash command "claudeos queue dump ClaudeOS")"
case_ "bash grep docs"         allow "$(qv Bash command "grep -n Queue.md ~/obsidian/SecondBrain/CLAUDE.md")"
case_ "bash unrelated"         allow "$(qv Bash command "cat README.md")"
C=$HOME/code/claudeos
I="$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents/SecondBrain/projects/ClaudeOS"
case_ "bash sed bare name, cwd in view"       deny  "$(qv Bash command "sed -i '' 's/a/b/' Queue.md" "$V")"
case_ "bash append bare name, cwd in view"    deny  "$(qv Bash command "echo x >> Queue.md" "$V")"
case_ "bash append unspaced, cwd in view"     deny  "$(qv Bash command "echo x >>Queue.md" "$V")"
case_ "bash dot-slash name, cwd in view"      deny  "$(qv Bash command "sed -i '' 's/a/b/' ./Queue.md" "$V")"
case_ "bash dotdot name, cwd under view"      deny  "$(qv Bash command "sed -i '' 's/a/b/' ../Queue.md" "$V/plans")"
case_ "bash bare name, cwd in icloud view"    deny  "$(qv Bash command "sed -i '' 's/a/b/' Queue.md" "$I")"
case_ "bash project name, cwd authority root" deny  "$(qv Bash command "sed -i '' 's/a/b/' ClaudeOS/Queue.md" "${Q%/*}")"
case_ "bash cd into view"                     deny  "$(qv Bash command "cd $V && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd into view, no cwd"             deny  "$(qv Bash command "cd $V && sed -i '' 's/a/b/' Queue.md")"
case_ "bash cd chain into view"               deny  "$(qv Bash command "cd ~/obsidian/SecondBrain && cd projects/ClaudeOS && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd semicolon chain into view"     deny  "$(qv Bash command "cd ~/obsidian/SecondBrain;cd projects/ClaudeOS;sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd quoted icloud view"            deny  "$(qv Bash command "cd '$I' && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd double-quoted icloud view"     deny  "$(qv Bash command "cd \"$I\" && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd in subshell into authority"    deny  "$(qv Bash command "(cd $Q; sed -i 's/a/b/' Queue.md)" "$C")"
case_ "bash unbalanced quote, cwd in view"    deny  "$(qv Bash command "echo 'x >> Queue.md" "$V")"
case_ "bash empty command, cwd in view"       allow "$(qv Bash command "" "$V")"
case_ "bash long command, bare name elsewhere" allow "$(qv Bash command "echo $(head -c 40000 /dev/zero | tr '\0' a); cat Queue.md" "$C")"
case_ "bash bare name elsewhere"              allow "$(qv Bash command "cat Queue.md" "$C/testdata")"
case_ "bash bare name, no cwd"                allow "$(qv Bash command "cat Queue.md")"
case_ "bash grep pattern elsewhere"           allow "$(qv Bash command "grep -rn Queue.md internal" "$C")"
case_ "bash cd elsewhere"                     allow "$(qv Bash command "cd internal/queue && cat testdata/Queue.md" "$C")"
case_ "bash other basename, cwd in view"      allow "$(qv Bash command "cat OldQueue.md" "$V")"
case_ "bash grep pattern, cwd vault root"     allow "$(qv Bash command "grep -n Queue.md CLAUDE.md" "$HOME/obsidian/SecondBrain")"
R=$HOME/obsidian/SecondBrain
case_ "edit lower-case name"                   deny  "$(qv Edit file_path "$V/queue.md")"
case_ "write lower-case name"                  deny  "$(qv Write file_path "$V/queue.md")"
case_ "write upper-case name"                  deny  "$(qv Write file_path "$V/QUEUE.MD")"
case_ "write lower-case directories"           deny  "$(qv Write file_path "$HOME/obsidian/secondbrain/Projects/claudeos/Queue.md")"
case_ "bash lower-case name, absolute"         deny  "$(qv Bash command "sed -i '' 's/a/b/' $V/queue.md")"
case_ "bash lower-case name, cwd in view"      deny  "$(qv Bash command "sed -i '' 's/a/b/' queue.md" "$V")"
case_ "bash empty quotes in name, absolute"    deny  "$(qv Bash command "sed -i '' 's/a/b/' $V/Que\"\"ue.md")"
case_ "bash backslash in name, absolute"       deny  "$(qv Bash command "sed -i '' 's/a/b/' $V/Que\\ue.md")"
case_ "bash quoted pieces, absolute"           deny  "$(qv Bash command "sed -i '' 's/a/b/' \"$V\"/'Queue.md'")"
case_ "bash continuation in name, absolute"    deny  "$(qv Bash command "$(printf 'sed -i "" s/a/b/ %s/Que\\\nue.md' "$V")")"
case_ "bash empty quotes in name, cwd in view" deny  "$(qv Bash command 'sed -i "" s/a/b/ Que""ue.md' "$V")"
case_ "bash cd -- into view"                   deny  "$(qv Bash command "cd -- $V && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd -P into view"                   deny  "$(qv Bash command "cd -P $V && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd -L into view"                   deny  "$(qv Bash command "cd -L $V && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd -P -- into view"                deny  "$(qv Bash command "cd -P -- $V && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd half-quoted home"               deny  "$(qv Bash command 'cd "$HOME"/obsidian/SecondBrain/projects/ClaudeOS && sed -i "" s/a/b/ Queue.md' "$C")"
case_ "bash cd half-quoted segment"            deny  "$(qv Bash command "cd ~/obsidian/\"SecondBrain\"/projects/ClaudeOS && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd escaped space, icloud view"     deny  "$(qv Bash command "cd $HOME/Library/Mobile\\ Documents/iCloud~md~obsidian/Documents/SecondBrain/projects/ClaudeOS && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "bash cd continuation into view"         deny  "$(qv Bash command "$(printf 'cd \\\n%s && sed -i "" s/a/b/ Queue.md' "$V")" "$C")"
case_ "bash dd of=, cwd in view"               deny  "$(qv Bash command "dd if=/dev/null of=Queue.md" "$V")"
case_ "bash --output=, cwd in view"            deny  "$(qv Bash command "curl -s x --output=Queue.md" "$V")"
case_ "bash brace list, cwd in view"           deny  "$(qv Bash command "sed -i '' 's/a/b/' {Queue.md,Inbox.md}" "$V")"
case_ "bash brace suffix, cwd in view"         deny  "$(qv Bash command "sed -i '' 's/a/b/' Queue.{md,bak}" "$V")"
case_ "bash brace list in a path, cwd vault root" deny "$(qv Bash command "sed -i '' 's/a/b/' projects/ClaudeOS/{Queue,Design}.md" "$R")"
case_ "bash two brace lists, cwd vault root"   deny  "$(qv Bash command "sed -i '' 's/a/b/' projects/{ClaudeOS,Tribemap}/{Queue,Inbox}.md" "$R")"
case_ "bash bracket glob, absolute"            deny  "$(qv Bash command "sed -i '' 's/a/b/' $V/Queue.m[d]")"
case_ "bash bracket glob, cwd in view"         deny  "$(qv Bash command "sed -i '' 's/a/b/' Queue.m[d]" "$V")"
case_ "bash question glob, cwd in view"        deny  "$(qv Bash command "sed -i '' 's/a/b/' Queue.m?" "$V")"
case_ "bash star glob, cwd in view"            deny  "$(qv Bash command "sed -i '' 's/a/b/' *.md" "$V")"
case_ "bash star glob in a path, cwd vault root" deny "$(qv Bash command "sed -i '' 's/a/b/' projects/ClaudeOS/*.md" "$R")"
case_ "bash bare star, cwd in authority"       deny  "$(qv Bash command "sed -i '' 's/a/b/' *" "$Q")"
case_ "bash 17 cd targets and a name"          deny  "$(qv Bash command "$(many 17 'cd d%d; ')cat Queue.md" "$C")"
case_ "bash 120 cd targets, 120 names"         deny  "$(qv Bash command "$(many 120 'cd d%d; ')$(many 120 'cat Queue.md; ')" "$C")"
case_ "bash 600 names elsewhere"               deny  "$(qv Bash command "$(many 600 'cat d%d/Queue.md; ')" "$C")"
case_ "bash overrun says why"                  1     "$(payload PreToolUse Bash command "$(many 17 'cd d%d; ')cat Queue.md" "$C" | guard guard-queue-views.sh | grep -c 'too many cd targets')"
case_ "bash plain deny keeps its reason"       0     "$(payload PreToolUse Bash command "sed -i '' 's/a/b/' Queue.md" "$V" | guard guard-queue-views.sh | grep -c 'too many cd targets')"
case_ "bash 16 cd targets and a name"          allow "$(qv Bash command "$(many 16 'cd d%d; ')cat Queue.md" "$C")"
case_ "bash 40 cd targets, no name"            allow "$(qv Bash command "$(many 40 'cd d%d; ')ls" "$C")"
case_ "bash 500 stars elsewhere"               allow "$(qv Bash command "printf '%s\n' $(many 500 '* ')" "$C")"
case_ "bash long word of slashes elsewhere"    allow "$(qv Bash command "echo $(many 8000 'a/')x; cd internal; cat Queue.md" "$C")"
case_ "bash 9 brace lists, cwd in view"        deny  "$(qv Bash command "sed -i '' 's/a/b/' {,}{,}{,}{,}{,}{,}{,}{,}{,}Queue.md" "$V")"
case_ "bash long brace word, cwd in view"      deny  "$(qv Bash command "sed -i '' 's/a/b/' {$(many 4100 'a'),Queue.md}" "$V")"
case_ "bash sort -o attached, cwd in view"     deny  "$(qv Bash command "sort -oQueue.md /dev/null" "$V")"
case_ "bash curl -o attached, cwd in view"     deny  "$(qv Bash command "curl -oQueue.md http://x" "$V")"
case_ "bash long brace word elsewhere"         allow "$(qv Bash command "cat {$(many 4100 'a'),x}" "$C")"
case_ "bash 9 brace lists elsewhere"           allow "$(qv Bash command "cat {,}{,}{,}{,}{,}{,}{,}{,}{,}x" "$C")"
case_ "bash sort -o other file, cwd in view"  allow "$(qv Bash command "sort -oOut.md /dev/null" "$V")"
case_ "bash sort -o attached elsewhere"        allow "$(qv Bash command "sort -oQueue.md /dev/null" "$C")"
case_ "bash lower-case name elsewhere"        allow "$(qv Bash command "cat queue.md" "$C")"
case_ "bash star glob elsewhere"               allow "$(qv Bash command "ls *.md" "$C")"
case_ "bash star glob under plans, cwd in view" allow "$(qv Bash command "ls plans/*.md" "$V")"
case_ "bash plans glob, cwd vault root"        allow "$(qv Bash command "wc -l projects/ClaudeOS/plans/*.md" "$R")"
case_ "bash projects listing, cwd vault root"  allow "$(qv Bash command "ls projects/*" "$R")"
case_ "bash other glob, cwd in view"           allow "$(qv Bash command "ls *.go" "$V")"
case_ "bash inbox by name, cwd in view"        allow "$(qv Bash command "cat Inbox.md" "$V")"
case_ "bash brace list elsewhere"              allow "$(qv Bash command "cat {Queue.md,README.md}" "$C/testdata")"
case_ "bash cd -- elsewhere"                   allow "$(qv Bash command "cd -- internal/queue && cat testdata/Queue.md" "$C")"
# --- reads: a bare reader on the view or the authority is allowed; a write spelling beside it, a wrapper or a redirect onto it is not
case_ "read cat absolute view"                 allow "$(qv Bash command "cat $V/Queue.md")"
case_ "read cat authority"                     allow "$(qv Bash command "cat $Q/Queue.md")"
case_ "read cat relative view"                 allow "$(qv Bash command "cat projects/ClaudeOS/Queue.md" "$R")"
case_ "read ls bare name, cwd in view"         allow "$(qv Bash command "ls Queue.md" "$V")"
case_ "read ls star glob, cwd in view"         allow "$(qv Bash command "ls *.md" "$V")"
case_ "read ls -la absolute view"              allow "$(qv Bash command "ls -la $V/Queue.md")"
case_ "read head, cwd in view"                 allow "$(qv Bash command "head -n 20 Queue.md" "$V")"
case_ "read tail dotdot name, cwd under view"  allow "$(qv Bash command "tail -5 ../Queue.md" "$V/plans")"
case_ "read wc absolute view"                  allow "$(qv Bash command "wc -l $V/Queue.md")"
case_ "read grep -n absolute view"             allow "$(qv Bash command "grep -n '^## ' $V/Queue.md")"
case_ "rg on the view"                         deny  "$(qv Bash command "rg -n 'q429' $V/Queue.md")"
case_ "read stat diff file cut nl"             allow "$(qv Bash command "stat $V/Queue.md; diff $V/Queue.md $Q/Queue.md; file $V/Queue.md; cut -c1-80 $V/Queue.md; nl $V/Queue.md")"
case_ "read cd into view"                      allow "$(qv Bash command "cd $V && cat Queue.md" "$C")"
case_ "read cd chain into view"                allow "$(qv Bash command "cd ~/obsidian/SecondBrain && cd projects/ClaudeOS && cat Queue.md" "$C")"
case_ "read cd quoted icloud view"             allow "$(qv Bash command "cd '$I' && cat Queue.md" "$C")"
case_ "read lower-case name, cwd in view"      allow "$(qv Bash command "cat queue.md" "$V")"
case_ "read quoted pieces, absolute"           allow "$(qv Bash command "cat \"$V\"/'Queue.md'")"
case_ "read brace list, cwd in view"           allow "$(qv Bash command "cat {Queue.md,Inbox.md}" "$V")"
case_ "read bare star, cwd in authority"       allow "$(qv Bash command "cat *" "$Q")"
case_ "read piped to a reader"                 allow "$(qv Bash command "cat $V/Queue.md | head -3")"
case_ "read piped to a writer"                 deny  "$(qv Bash command "cat $V/Queue.md | tee /tmp/out")"
case_ "read redirected elsewhere"              allow "$(qv Bash command "cat $V/Queue.md > /tmp/out 2>&1")"
case_ "read beside an unlisted program"        deny  "$(qv Bash command "cat $V/Queue.md; echo x >> /tmp/out")"
case_ "read input redirect from the view"      allow "$(qv Bash command "wc -l < $V/Queue.md")"
case_ "read then a write"                      deny  "$(qv Bash command "cat Queue.md; sed -i '' 's/a/b/' Queue.md" "$V")"
case_ "read then a move"                       deny  "$(qv Bash command "cat $V/Queue.md && mv $V/Queue.md /tmp/x")"
case_ "read redirected onto the view"          deny  "$(qv Bash command "cat $V/Inbox.md > $V/Queue.md")"
case_ "read appended onto the view, cwd in view" deny "$(qv Bash command "grep x Inbox.md >> Queue.md" "$V")"
case_ "read appended unspaced onto the view"   deny  "$(qv Bash command "grep x Inbox.md >>Queue.md" "$V")"
case_ "read clobbered onto the view"           deny  "$(qv Bash command "cat x >| $V/Queue.md")"
case_ "read-write redirect onto the view"      deny  "$(qv Bash command "cat 0<> $V/Queue.md")"
case_ "read redirected onto a glob, cwd in view" deny "$(qv Bash command "cat x > *.md" "$V")"
case_ "reader by path"                         deny  "$(qv Bash command "/bin/cat $V/Queue.md")"
case_ "reader by relative path"                deny  "$(qv Bash command "./cat $V/Queue.md")"
case_ "reader behind sudo"                     deny  "$(qv Bash command "sudo cat $V/Queue.md")"
case_ "reader behind env assignment"           deny  "$(qv Bash command "LC_ALL=C cat $V/Queue.md")"
case_ "reader behind xargs"                    deny  "$(qv Bash command "echo $V/Queue.md | xargs cat")"
case_ "read in a command substitution"         deny  "$(qv Bash command "echo \$(cat $V/Queue.md)")"
case_ "reader output into a writer, substitution" deny "$(qv Bash command "sed -i s/a/b/ \$(ls Queue.md)" "$V")"
case_ "reader output into a writer, backticks" deny  "$(qv Bash command "rm \`ls Queue.md\`" "$V")"
case_ "reader output into a writer, tee"       deny  "$(qv Bash command "tee \$(ls Queue.md)" "$V")"
case_ "reader piped to xargs sed"              deny  "$(qv Bash command "ls Queue.md | xargs sed -i s/a/b/" "$V")"
case_ "reader piped to xargs rm"               deny  "$(qv Bash command "grep -l x Queue.md | xargs rm" "$V")"
case_ "env assignment named like a reader"     deny  "$(qv Bash command "cat=1 sed -i s/a/b/ Queue.md" "$V")"
case_ "env assignment named like ls"           deny  "$(qv Bash command "ls=x rm Queue.md" "$V")"
case_ "reader redefined as a function"         deny  "$(qv Bash command "cat(){ sed -i s/a/b/ \"\$@\"; }; cat Queue.md" "$V")"
case_ "reader found through a new PATH"        deny  "$(qv Bash command "PATH=/tmp/evil:\$PATH; cat Queue.md" "$V")"
case_ "reader aliased"                         deny  "$(qv Bash command "alias cat='sed -i s/a/b/'; cat Queue.md" "$V")"
case_ "zsh clobber redirect onto the view"     deny  "$(qv Bash command "cat x >! Queue.md" "$V")"
case_ "zsh append clobber redirect onto the view" deny "$(qv Bash command "cat x >>! Queue.md" "$V")"
case_ "reader output as a redirect target"     deny  "$(qv Bash command "cat x > \$(ls Queue.md)" "$V")"
case_ "reader output as an unspaced redirect target" deny "$(qv Bash command "cat x >\$(ls Queue.md)" "$V")"
case_ "reader glob output as a redirect target" deny "$(qv Bash command "cat x > \$(ls Q*)" "$V")"
case_ "process substitution as a redirect target" deny "$(qv Bash command "cat x > >(ls Queue.md)" "$V")"
case_ "redirect onto a glob group"             deny  "$(qv Bash command "cat x >Queue.md(|ls)" "$V")"
case_ "zsh clobber redirect, unspaced"         deny  "$(qv Bash command "cat x >!Queue.md" "$V")"
case_ "zsh append clobber redirect, unspaced"  deny  "$(qv Bash command "echo x >>!Queue.md" "$V")"
case_ "zsh &>! redirect, unspaced"             deny  "$(qv Bash command "echo x &>!Queue.md" "$V")"
case_ "zsh glob group names the view"          deny  "$(qv Bash command "sed -i s/a/b/ Queue.m(d|x)" "$V")"
case_ "zsh single-letter group names the view" deny  "$(qv Bash command "tee Q(u)eue.md" "$V")"
case_ "zsh leading group names the view"       deny  "$(qv Bash command "cp x (Queue).md" "$V")"
case_ "zsh empty alternative names the view"   deny  "$(qv Bash command "cp x Queue.m(|d)" "$V")"
case_ "glob group elsewhere"                   allow "$(qv Bash command "sed -i s/a/b/ Queue.m(d|x)" "$C")"
case_ "zsh glob qualifier runs code"          deny  "$(qv Bash command "ls Queue.md(e:'touch /tmp/zz':)" "$V")"
case_ "redirect onto a 4100-character path"    deny  "$(qv Bash command "echo x > /$(many 4100 'a')/../${V#/}/Queue.md")"
case_ "write via a 4100-character path"        deny  "$(qv Bash command "sed -i s/a/b/ /$(many 4100 'a')/../${V#/}/Queue.md")"
case_ "sed -n on the view"                     deny  "$(qv Bash command "sed -n '1,5p' $V/Queue.md")"
case_ "sed w onto the view"                    deny  "$(qv Bash command "sed 'w $V/Queue.md' /tmp/x")"
case_ "rg --pre on the view"                   deny  "$(qv Bash command "rg --pre 'sed -i s/a/b/' x $V/Queue.md")"
case_ "rg --pre= on the view"                  deny  "$(qv Bash command "rg --pre=cmd x $V/Queue.md")"
case_ "awk on the view"                        deny  "$(qv Bash command "awk '{print > FILENAME}' $V/Queue.md")"
case_ "sort -o onto the view"                  deny  "$(qv Bash command "sort -o $V/Queue.md /dev/null")"
case_ "tee onto the view"                      deny  "$(qv Bash command "cat x | tee $V/Queue.md")"
case_ "cp onto the view"                       deny  "$(qv Bash command "cp x $V/Queue.md")"
case_ "cp from the view"                       deny  "$(qv Bash command "cp $V/Queue.md /tmp/x")"
case_ "python on the view"                     deny  "$(qv Bash command "python3 -c 'open(\"$V/Queue.md\",\"w\")'")"
case_ "read, write in process substitution"    deny  "$(qv Bash command "cat <(sed -i '' 's/a/b/' $V/Queue.md)")"
case_ "read in a group"                        deny  "$(qv Bash command "{ cat $V/Queue.md; }")"
case_ "read overrun still denies"              deny  "$(qv Bash command "$(many 17 'cd d%d; ')cat Queue.md" "$C")"
case_ "read 65 redirects beside a name, cwd in view" deny "$(qv Bash command "cat Queue.md $(many 65 '> /tmp/x%d ')" "$V")"
case_ "read 64 redirects beside a name, cwd in view" allow "$(qv Bash command "cat Queue.md $(many 64 '> /tmp/x%d ')" "$V")"
case_ "read 65 redirects, no name"             allow "$(qv Bash command "echo x $(many 65 '> /tmp/x%d ')" "$V")"
case_ "read 4097 segments beside a name, cwd in view" deny "$(qv Bash command "$(many 4096 'ls %d; ')cat Queue.md" "$V")"
case_ "read 4096 segments beside a name, cwd in view" allow "$(qv Bash command "$(many 4095 'ls %d; ')cat Queue.md" "$V")"
case_ "read 4097 segments, no name"            allow "$(qv Bash command "$(many 4096 'echo %d; ')ls" "$V")"
case_ "read redirect overrun says why"         1     "$(payload PreToolUse Bash command "cat Queue.md $(many 65 '> /tmp/x%d ')" "$V" | guard guard-queue-views.sh | grep -c 'too many cd targets, too many > redirects')"
case_ "read deny names the readers"            1     "$(payload PreToolUse Bash command "sed -n p $V/Queue.md" | guard guard-queue-views.sh | grep -c 'plain read')"
case_ "gemini shell read view"                 allow "$(gv run_shell_command command "cat $V/Queue.md")"
case_ "gemini shell read star glob, cwd in view" allow "$(gv run_shell_command command "ls *.md" "$V")"
case_ "gemini shell read then a write"         deny  "$(gv run_shell_command command "cat Queue.md; sed -i 's/a/b/' Queue.md" "$V")"
case_ "queue guard bad input"  allow "$(printf 'garbage' | guard guard-queue-views.sh | decision)"
case_ "codex bash sed authority"             deny  "$(qv Bash command "sed -i 's/a/b/' $Q/Queue.md")"
case_ "codex apply_patch update view"        deny  "$(qv apply_patch command "$(patch Update "$V/Queue.md")")"
case_ "codex apply_patch add relative view"  deny  "$(qv apply_patch command "$(patch Add projects/ClaudeOS/Queue.md)" "$HOME/obsidian/SecondBrain")"
case_ "codex apply_patch body mentions view" deny  "$(qv apply_patch command "$(printf '*** Begin Patch\n*** Update File: README.md\n@@\n-a\n+see projects/ClaudeOS/Queue.md\n*** End Patch\n')" "$HOME/code/claudeos")"
case_ "codex apply_patch unrelated"          allow "$(qv apply_patch command "$(patch Update README.md)" "$HOME/code/claudeos")"
case_ "codex apply_patch move unrelated"     allow "$(qv apply_patch command "$(mpatch README.md docs/README.md)" "$HOME/code/claudeos")"
case_ "codex apply_patch context mentions view"      allow "$(qv apply_patch command "$(printf '*** Begin Patch\n*** Update File: README.md\n@@\n see projects/ClaudeOS/Queue.md\n-a\n+b\n*** End Patch\n')" "$HOME/code/claudeos")"
case_ "codex apply_patch removed line mentions view" allow "$(qv apply_patch command "$(printf '*** Begin Patch\n*** Update File: README.md\n@@\n-see projects/ClaudeOS/Queue.md\n+b\n*** End Patch\n')" "$HOME/code/claudeos")"
case_ "codex apply_patch relative authority, no cwd" deny  "$(qv apply_patch command "$(patch Update ClaudeOS/Queue.md)")"
case_ "codex apply_patch relative unrelated, no cwd" allow "$(qv apply_patch command "$(patch Update README.md)")"
case_ "gemini replace relative authority, no cwd"    deny  "$(gv replace file_path ClaudeOS/Queue.md)"
case_ "gemini write_file view"     deny  "$(gv write_file file_path "$V/Queue.md")"
case_ "gemini shell sed view"      deny  "$(gv run_shell_command command "sed -i '' 's/a/b/' $V/Queue.md")"
case_ "gemini shell unrelated"     allow "$(gv run_shell_command command "cat README.md")"
case_ "gemini shell bare name, cwd in view" deny  "$(gv run_shell_command command "sed -i 's/a/b/' Queue.md" "$V")"
case_ "gemini shell cd into view"           deny  "$(gv run_shell_command command "cd $V && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "gemini shell bare name elsewhere"    allow "$(gv run_shell_command command "cat Queue.md" "$C")"
case_ "gemini shell cd -- into view"         deny  "$(gv run_shell_command command "cd -- $V && sed -i '' 's/a/b/' Queue.md" "$C")"
case_ "gemini shell star glob, cwd in view"  deny  "$(gv run_shell_command command "sed -i '' 's/a/b/' *.md" "$V")"
case_ "gemini write_file lower-case view"    deny  "$(gv write_file file_path "$V/queue.md")"
case_ "codex apply_patch lower-case view"    deny  "$(qv apply_patch command "$(patch Update "$V/queue.md")")"
case_ "queue guard unreadable command"       deny  "$(unreadable PreToolUse Bash | guard guard-queue-views.sh | decision)"
case_ "queue guard unreadable patch"         deny  "$(unreadable PreToolUse apply_patch | guard guard-queue-views.sh | decision)"
case_ "queue guard unreadable file path"     deny  "$(unreadable PreToolUse Write | guard guard-queue-views.sh | decision)"
case_ "gemini queue unreadable command shape" gemini "$(unreadable BeforeTool run_shell_command | guard guard-queue-views.sh | shape)"
case_ "gemini queue deny shape"    gemini     "$(payload BeforeTool write_file file_path "$V/Queue.md" | guard guard-queue-views.sh | shape)"
case_ "gemini queue allow shape"   empty-json "$(payload BeforeTool write_file file_path "$V/Inbox.md" | guard guard-queue-views.sh | shape)"
case_ "claude queue deny shape"    claude     "$(payload PreToolUse Write file_path "$V/Queue.md" | guard guard-queue-views.sh | shape)"
case_ "claude queue allow shape"   silent     "$(payload PreToolUse Write file_path "$V/Inbox.md" | guard guard-queue-views.sh | shape)"
case_ "gh pr merge"            deny  "$(mg "gh pr merge 12")"
case_ "gh -R pr merge"         deny  "$(mg "gh -R pablobfonseca/claudeos pr merge 12 --squash")"
case_ "gh pr merge --auto"     deny  "$(mg "gh pr merge --auto 12")"
case_ "rest merge"             deny  "$(mg "gh api -X PUT repos/o/r/pulls/12/merge")"
case_ "graphql merge"          deny  "$(mg 'gh api graphql -f query="mutation { mergePullRequest(input:{pullRequestId:\"x\"}) { clientMutationId } }"')"
case_ "graphql auto-merge"     deny  "$(mg 'gh api graphql -f query="mutation { enablePullRequestAutoMerge(input:{pullRequestId:\"x\"}) { clientMutationId } }"')"
case_ "gh pr create"           allow "$(mg "gh pr create --assignee @me")"
case_ "gh pr view"             allow "$(mg "gh pr view 12")"
case_ "git merge local"        allow "$(mg "git merge origin/master")"
case_ "gh pr list search"      allow "$(mg "gh pr list --search merge")"
case_ "gh by absolute path"    deny  "$(mg "/opt/homebrew/bin/gh pr merge 12")"
case_ "gh by relative path"    deny  "$(mg "./bin/gh pr merge 12")"
case_ "gh quoted"              deny  "$(mg '"gh" pr merge 12')"
case_ "gh by which"            deny  "$(mg '$(which gh) pr merge 12')"
case_ "gh by backtick which"   deny  "$(mg '`which gh` pr merge 12')"
case_ "gh pr merge, semicolon" deny  "$(mg "gh pr merge; echo done")"
case_ "gh pr merge, subshell"  deny  "$(mg "(cd repo && gh pr merge)")"
case_ "gh pr merge, piped"     deny  "$(mg "gh pr merge|tee log")"
case_ "gh pr merge --help"     allow "$(mg "gh pr merge --help")"
case_ "help, then a merge"     deny  "$(mg "gh pr merge --help; gh pr merge 12")"
case_ "help, merge on line 2"  deny  "$(mg "$(printf 'gh pr merge --help\ngh pr merge 12')")"
case_ "help piped"             deny  "$(mg "gh pr merge --help | head")"
case_ "help beside a number"   deny  "$(mg "gh pr merge 12 --help")"
case_ "help by absolute path"  deny  "$(mg "/opt/homebrew/bin/gh pr merge --help")"
case_ "gh help pr merge"       deny  "$(mg "gh help pr merge")"
case_ "gh search merge-queue"  allow "$(mg "gh issue list --search 'pr merge-queue'")"
case_ "flag between pr and merge"      deny  "$(mg "gh pr -R o/r merge 12")"
case_ "long flag between pr and merge" deny  "$(mg "gh pr --repo o/r merge 12")"
case_ "flag= between pr and merge"     deny  "$(mg "gh pr --repo=o/r merge 12")"
case_ "merge in double quotes"         deny  "$(mg 'gh pr "merge" 12')"
case_ "merge in single quotes"         deny  "$(mg "gh pr 'merge' 12")"
case_ "merge split by quotes"          deny  "$(mg 'gh pr mer""ge 12')"
case_ "merge with a backslash"         deny  "$(mg 'gh pr m\erge 12')"
case_ "pr in quotes"                   deny  "$(mg 'gh "pr" merge 12')"
case_ "gh split by quotes"             deny  "$(mg 'g"h" pr merge 12')"
case_ "gh with a backslash"            deny  "$(mg 'g\h pr merge 12')"
case_ "continuation between words"     deny  "$(mg "$(printf 'gh pr \\\n merge 12')")"
case_ "continuation inside merge"      deny  "$(mg "$(printf 'gh pr mer\\\nge 12')")"
case_ "gh upper case"                  deny  "$(mg "GH pr merge 12")"
case_ "gh mixed case"                  deny  "$(mg "Gh pr merge 12")"
case_ "gh last, by xargs"              deny  "$(mg "echo pr merge 12 | xargs gh")"
case_ "gh before a pipe"               deny  "$(mg "echo pr merge 12 | xargs gh|cat")"
case_ "gh before a redirect"           deny  "$(mg "echo pr merge 12 | xargs gh>log")"
case_ "gh before a semicolon"          deny  "$(mg "echo pr merge 12 | xargs gh;")"
case_ "gh held in a variable"          deny  "$(mg 'g=gh; $g pr merge 12')"
case_ "rest merge split by quotes"     deny  "$(mg 'gh api -X PUT repos/o/r/pulls/12/"merge"')"
case_ "graphql merge split by quotes"  deny  "$(mg "gh api graphql -f query='mutation { merge'\"PullRequest\"'(input:{}) { clientMutationId } }'")"
case_ "graphql enqueue"                deny  "$(mg 'gh api graphql -f query="mutation { enqueuePullRequest(input:{}) { clientMutationId } }"')"
case_ "alias for pr merge"            deny  "$(mg "gh alias set m 'pr merge'")"
case_ "merge guard unreadable command" deny  "$(unreadable PreToolUse Bash | guard guard-merge.sh | decision)"
case_ "flag between pr and view"       allow "$(mg "gh pr -R o/r view 12")"
case_ "flag before pr list search"     allow "$(mg "gh pr -R o/r list --search merge")"
case_ "gh pr view mergeable"           allow "$(mg "gh pr view 12 --json mergeable")"
case_ "gh-dash beside pr merge"        allow "$(mg "gh-dash --help; git log --grep 'pr merge'")"
case_ "git log grep pr merge"          allow "$(mg "git log --grep 'pr merge'")"
case_ "merge guard bad input"  allow "$(printf 'garbage' | guard guard-merge.sh | decision)"
case_ "gemini gh pr merge"         deny       "$(gm "gh pr merge 12")"
case_ "gemini gh -R pr merge"      deny       "$(gm "gh -R pablobfonseca/claudeos pr merge 12 --squash")"
case_ "gemini gh pr view"          allow      "$(gm "gh pr view 12")"
case_ "gemini gh by absolute path" deny       "$(gm "/opt/homebrew/bin/gh pr merge 12")"
case_ "gemini gh by relative path" deny       "$(gm "./bin/gh pr merge 12")"
case_ "gemini gh pr merge --help"  allow      "$(gm "gh pr merge --help")"
case_ "gemini flag between pr and merge" deny  "$(gm "gh pr -R o/r merge 12")"
case_ "gemini gh upper case"             deny  "$(gm "GH pr merge 12")"
case_ "gemini merge unreadable command shape" gemini "$(unreadable BeforeTool run_shell_command | guard guard-merge.sh | shape)"
case_ "gemini merge help shape"    empty-json "$(payload BeforeTool run_shell_command command "gh pr merge --help" | guard guard-merge.sh | shape)"
case_ "gemini merge deny shape"    gemini     "$(payload BeforeTool run_shell_command command "gh pr merge 12" | guard guard-merge.sh | shape)"
case_ "gemini merge allow shape"   empty-json "$(payload BeforeTool run_shell_command command "gh pr view 12" | guard guard-merge.sh | shape)"
case_ "claude merge deny shape"    claude     "$(payload PreToolUse Bash command "gh pr merge 12" | guard guard-merge.sh | shape)"
case_ "claude merge allow shape"   silent     "$(payload PreToolUse Bash command "gh pr view 12" | guard guard-merge.sh | shape)"
case_ "merge guard bad input, gemini shape" silent "$(printf 'garbage' | guard guard-merge.sh | shape)"
if [[ -z ${GUARD_BASH:-} && -x /bin/bash ]]; then
  GUARD_BASH=/bin/bash "$0" | sed "s|^|[/bin/bash] |"
  (( PIPESTATUS[0] == 0 )) || fail=1
fi
exit $fail
