require("kulala").setup()

vim.keymap.set("n", "<leader>rm", function()
  require("kulala").scratchpad()
end, { desc = "Open request scratchpad" })
vim.keymap.set("n", "<C-c><C-c>", function()
  require("kulala").run()
end, { desc = "Run request" })
vim.keymap.set("n", "<C-c>kt", function()
  require("kulala").toggle_view()
end, { desc = "Kulala Toggle View" })
vim.keymap.set("n", "<C-c>ks", function()
  require("kulala").search()
end, { desc = "Kulala Search" })
