#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title Copy IP
# @raycast.mode silent

# Optional parameters:
# @raycast.icon 🛜

# Documentation:
# @raycast.author pablobfonseca
# @raycast.authorURL https://raycast.com/pablobfonseca

curl -s ifconfig.me | pbcopy
echo "IP Copied!"
