return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = { "BufReadPost", "BufNewFile" },
  cmd = { "TSInstall", "TSUpdate", "TSUpdateSync" },
  opts = {
    ensure_installed = {
      "css",
      "dockerfile",
      "elm",
      "gitcommit",
      "go",
      "haskell",
      "html",
      "javascript",
      "json",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "ocaml",
      "python",
      "ruby",
      "rust",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
    },
    highlight = {
      enable = true,
    },
    indent = {
      enable = true,
    },
    endwise = {
      enable = true,
    },
    sync_install = false,
    auto_install = true,
    incremental_selection = {
      enable = true,
      keymaps = {},
    },
  },
  main = "nvim-treesitter",
}
