# 
#          _     
#  _______| |__  
# |_  / __| '_ \ 
#  / /\__ \ | | |
# /___|___/_| |_|
#                
# 

# set -o vi
export VISUAL='vim'
export EDITOR=$VISUAL

export BUNDLER_EDITOR='vim'

export HOMEBREW_CASK_OPTS="--appdir=/Applications"

ZSH_THEME="spaceship"

bgnotify_threshold=4
function bgnotify_formatted {
  ## $1=exit_status, $2=command, $3=elapsed_time
  [ $1 -eq 0 ] && title="Command has been executed "
  bgnotify "$title -- after $3 s" "$2";
}

export ZSH=/Users/pablobfonseca/.oh-my-zsh
plugins=(
  brew
  osx
  bgnotify
  web-search
  z
)

source $ZSH/oh-my-zsh.sh

# Allow completing of the remainder of a command
bindkey "^N" insert-last-word

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

# Enable completion
autoload -U compinit
compinit

# Add paths
export DOTFILES=$HOME/.dotfiles
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$HOME/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export PATH=/usr/local/share/npm/bin:$PATH

# Source another files
for zsh_source in /Users/pablobfonseca/.zsh/config/*.zsh; do
  source $zsh_source
done

# Dont' expand aliases _before_ completion
setopt complete_aliases

# Add current directory bin
export PATH=$PATH:bin

# Heroku toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export PATH=$PATH:/usr/local/opt/go/libexec/bin
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Postgres
export PATH="/Applications/Postgres.app/Contents/Versions/10/bin:$PATH"

# Edit the current line in $EDITOR
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^x^e' edit-command-line

# Auto-suggestions
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Cdpath for quick navigation
setopt auto_cd
cdpath=($HOME/code $DOTFILES)

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/plugins/zsh-interactive-cd.plugin.zsh

export PATH="/usr/local/opt/imagemagick@6/bin:$PATH"

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
# prompt spaceship

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"


# Go
export GOPATH=$HOME/code/go-workspace
export GOROOT=/usr/local/opt/go/libexec
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin